apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-demo
  name: user-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-demo
  template:
    metadata:
      labels:
        app: user-demo
    spec:
      containers:
        - image: docker.io/user-demo:latest
          name: user-demo
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-demo
spec:
  selector:
    app: user-demo
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: user-demo
spec:
  tls:
    termination: edge
  port:
    targetPort: http
  to:
    kind: Service
    name: user-demo
    weight: 100
  wildcardPolicy: None

